// spotlightTour.ts
// Generated by vibe-walk emit_tour_module — edit freely.
// SSR guard: driver.js is browser-only; this module is client-side only.
// Do NOT import server-side (Next.js: use dynamic import with ssr: false,
// or call only inside useEffect / onClick handlers).
import { driver } from 'driver.js';
import 'driver.js/dist/driver.css';
import { SPOTLIGHT_STEPS } from './spotlightSteps';

/**
 * Starts the spotlight tour. `onDone` runs once when the tour is destroyed —
 * covers finishing the last step, the close button, and ESC.
 *
 * Replay entry point: call this function at any time (from a help menu,
 * a "Take the Tour" button, etc.) — it is persistent and ungated.
 *
 * SSR: always call this inside a browser context (useEffect, onClick, etc.).
 * typeof window guard is enforced below.
 */
export function startSpotlightTour(onDone?: () => void): void {
  // SSR guard — driver.js requires a browser DOM; bail out on SSR/SSG renders.
  if (typeof window === 'undefined') return;

  const tour = driver({
    showProgress: true,
    showButtons: ['next', 'previous', 'close'],
    popoverClass: 'celestia3-spotlight',
    steps: SPOTLIGHT_STEPS,
    onDestroyed: () => {
      onDone?.();
    },
  });
  tour.drive();
}

/**
 * Replay export — persistent, ungated. Wire to any "Take the Tour" / help
 * surface. No first-run gate; fires any time the user wants a replay.
 * Alias of startSpotlightTour with no onDone callback.
 */
export const replaySpotlightTour = (): void => startSpotlightTour();
