// spotlightSteps.ts
// Generated by vibe-walk emit_tour_module — edit freely.
import type { DriveStep } from 'driver.js';

export const SPOTLIGHT_STEPS: DriveStep[] = [
  {
    element: '[data-tour="natal-chart"]',
    popover: {
      title: 'NatalCompass',
      description: 'Your sky at birth, in 3D. Hover planets and inspect aspects — the heart of Celestia',
      side: 'right',
      align: 'start',
    },
  },
  {
    element: '[data-tour="sidebar-nav"]',
    popover: {
      title: 'Sidebar nav',
      description: 'Every feature lives here — your chart, tarot, rituals, and more',
      side: 'bottom',
      align: 'start',
    },
  },
  {
    element: '[data-tour="progression-bar"]',
    popover: {
      title: 'Progression bar',
      description: 'Explore to earn XP. Leveling unlocks the Adept and Archon tools',
      side: 'bottom',
      align: 'center',
    },
  },
  {
    element: '[data-tour="daily-pulse"]',
    popover: {
      title: 'Daily pulse',
      description: 'A fresh numerology focus for today — a new one every day',
      side: 'top',
      align: 'center',
    },
  },
  {
    element: '[data-tour="numerology-cards"]',
    popover: {
      title: 'Numerology cards',
      description: 'Life Path, Destiny, and today\'s active number. Tap any for the deep dive',
      side: 'left',
      align: 'end',
    },
  },
];
