// tourAnalytics.ts
// Generated by vibe-walk emit_analytics — edit freely.
//
// WIRING: replace the trackTourEvent stub with your analytics provider call.
// All 6 tour events flow through this single function — wire it once,
// and every event lands in your dashboard.
//
// See TOUR_ANALYTICS.md for the full wiring guide + provider examples.

// ---------------------------------------------------------------------------
// Host-agnostic seam — replace this stub with your analytics provider call.
// ---------------------------------------------------------------------------

/**
 * trackTourEvent — the single analytics seam for the spotlight tour.
 *
 * Replace this stub:
 *
 *   export function trackTourEvent(event: string, payload: Record<string, unknown>): void {
 *     yourAnalyticsProvider.track(event, payload);
 *   }
 *
 * event: one of the 6 tour event names (see TOUR_ANALYTICS.md)
 * payload: event-specific properties (step_index, step_name, tour_id, etc.)
 */
export function trackTourEvent(
  event: string,
  payload: Record<string, unknown> = {},
): void {
  // STUB — replace with your analytics provider call.
  // This no-op prevents console noise in production until you wire it.
  if (process.env.NODE_ENV === 'development') {
    console.debug('[vibe-walk analytics]', event, payload);
  }
}

// ---------------------------------------------------------------------------
// Driver.js callback handlers — wire these into your driver() config.
//
// Usage: pass these as callbacks when constructing your driver() instance
// (alongside the SPOTLIGHT_STEPS from spotlightTour.ts).
//
// Example integration in spotlightTour.ts:
//   import { onHighlightStarted, onNextClick, onDestroyStarted, emitTourStarted }
//     from './tourAnalytics';
//
//   const tour = driver({
//     steps: SPOTLIGHT_STEPS,
//     onHighlightStarted,
//     onNextClick,
//     onDestroyStarted,
//     onDestroyed: onDone,
//   });
//   emitTourStarted({ tour_id: 'spotlight' });
//   tour.drive();
// ---------------------------------------------------------------------------

const TOTAL_STEPS = 6;

/**
 * emitTourStarted — call immediately before tour.drive().
 * Event: tour_started
 */
export function emitTourStarted(payload: Record<string, unknown> = {}): void {
  trackTourEvent('tour_started', { total_steps: TOTAL_STEPS, ...payload });
}

/**
 * onHighlightStarted — Driver.js callback fired when a step becomes active.
 * Event: tour_step_viewed
 *
 * Wire to driver({ onHighlightStarted })
 */
export function onHighlightStarted(
  element: Element | undefined,
  step: { index: number; [key: string]: unknown },
  _options: unknown,
): void {
  trackTourEvent('tour_step_viewed', {
    step_index: step.index,
    step_name: (step as { popover?: { title?: string } }).popover?.title ?? '',
    total_steps: TOTAL_STEPS,
  });
}

/**
 * onNextClick — Driver.js callback fired when the user clicks "Next".
 * Event: tour_step_advanced
 *
 * Wire to driver({ onNextClick })
 */
export function onNextClick(
  element: Element | undefined,
  step: { index: number; [key: string]: unknown },
  _options: unknown,
): void {
  trackTourEvent('tour_step_advanced', {
    step_index: step.index,
    step_name: (step as { popover?: { title?: string } }).popover?.title ?? '',
    total_steps: TOTAL_STEPS,
  });
}

/**
 * onDestroyStarted — Driver.js callback fired when the tour is about to be
 * destroyed (close button, ESC, or natural completion of last step).
 *
 * Distinguishes tour_skipped from tour_completed by checking whether the
 * active step index is the last step.
 *
 *   - On the last step  → tour_completed (user saw every step)
 *   - Before last step  → tour_skipped   (user bailed early)
 *
 * Wire to driver({ onDestroyStarted })
 */
export function onDestroyStarted(
  element: Element | undefined,
  step: { index: number; [key: string]: unknown },
  _options: unknown,
): void {
  const isLastStep = step.index >= TOTAL_STEPS - 1;
  if (isLastStep) {
    trackTourEvent('tour_completed', {
      step_index: step.index,
      total_steps: TOTAL_STEPS,
    });
  } else {
    trackTourEvent('tour_skipped', {
      step_index: step.index,
      skipped_at_step: step.index + 1,
      total_steps: TOTAL_STEPS,
    });
  }
}

/**
 * emitTourReplayed — call at the point the user triggers a replay
 * (e.g., from a help menu or "Take the Tour Again" button).
 * Event: tour_replayed
 *
 * Call this before invoking replaySpotlightTour() from spotlightTour.ts.
 */
export function emitTourReplayed(payload: Record<string, unknown> = {}): void {
  trackTourEvent('tour_replayed', { total_steps: TOTAL_STEPS, ...payload });
}
